baseURL = 'https://superb-meringue-5ce60c.netlify.app/'
languageCode = 'de-de'
title = 'Kleintierpraxis Dr. Heike Möbius'

assetdir = 'static'

[markup.goldmark.renderer]
  unsafe = true

enableGitInfo = true
