baseURL = 'https://kuchromik.github.io/ta-moebius/'
languageCode = 'de-de'
title = 'Kleintierpraxis Dr. Heike Möbius'

assetdir = 'static'

[markup.goldmark.renderer]
  unsafe = true

enableGitInfo = true
